//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosedeDursunDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentReply
    {
        public int Id { get; set; }
        public int Author_Id { get; set; }
        public string Text { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModifedTime { get; set; }
        public int Comment_Id { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Comment Comment { get; set; }
    }
}
